### ISSUE TITLE
option to write file to stdout?

### ISSUE THREAD

**Issue by karme** [jeromelesaux/dsk#13]
I am trying to integrate dsk support into emacs arc-mode. There it would be useful if the file written by -get could be written to stdout.

**Comment by jeromelesaux** [comment]
Adding the -stdout will be ok for you ?

**Comment by jeromelesaux** [comment]
Sounds good for me. I’ll add this option in next release. For sur tomorrow.

**Comment by jeromelesaux** [comment]
new version is available https://github.com/jeromelesaux/dsk/releases/tag/v0.28 
new option -stdout is added.

**Comment by karme** [comment]
Looks like I have a general misunderstanding here:
If I add a basic file with put does it get a header?

Example:

```
$ cat test-bas.sh
#!/bin/bash -xe
dsk -dsk test.dsk -format -force
cat > test.bas <<EOF
10 print "hello"
20 goto 10
EOF
unix2dos test.bas
cat test.bas
dsk -dsk test.dsk -list
X=$(md5sum test.bas|cut -f 1 -d " ")
dsk -dsk test.dsk -put test.bas
rm -v test.bas
dsk -dsk test.dsk -get test.bas -stdout > test.bas
Y=$(md5sum test.bas|cut -f 1 -d " ")
if [ "$X" = "$Y" ]; then
    echo OK.
else
    echo MISMATCH
    hd test.bas
    exit 1
fi
$ ./test-bas.sh
+ dsk -dsk test.dsk -format -force
DSK cli version [0.28]
Made by Sid (ImpAct)
Formating number of sectors (9), tracks (39), head number (1)
Dsk file (test.dsk)
+ cat
+ unix2dos test.bas
unix2dos: converting file test.bas to DOS format...
+ cat test.bas
10 print "hello"
20 goto 10
+ dsk -dsk test.dsk -list
DSK cli version [0.28]
Made by Sid (ImpAct)
Dsk file (test.dsk)
Dsk 000 Ko used
Dsk 000 Ko used
++ md5sum test.bas
++ cut -f 1 -d ' '
+ X=e8c3630a87ce2ccf5741b13acdf78c38
+ dsk -dsk test.dsk -put test.bas
DSK cli version [0.28]
Made by Sid (ImpAct)
Dsk file (test.dsk)
file (test.bas) read (30 bytes).
No header found for file :test.bas, error :unexpected EOF
Create header... (test.bas)
DSK path [test.dsk]
ACTION: Action on DSK [put ascii] on amsdos file [test.bas]
INFO:   execute address [#0000], loading address [#0000]

+ rm -v test.bas
removed 'test.bas'
+ dsk -dsk test.dsk -get test.bas -stdout
DSK cli version [0.28]
Made by Sid (ImpAct)
Dsk file (test.dsk)
++ md5sum test.bas
++ cut -f 1 -d ' '
+ Y=4c8448ae521a46bd0cdd9dff3f2e8790
+ '[' e8c3630a87ce2ccf5741b13acdf78c38 = 4c8448ae521a46bd0cdd9dff3f2e8790 ']'
+ echo MISMATCH
MISMATCH
+ hd test.bas
00000000  31 30 20 70 72 69 6e 74  20 22 68 65 6c 6c 6f 22  |10 print "hello"|
00000010  0d 0a 32 30 20 67 6f 74  6f 20 31 30 0d 0a 1a 00  |..20 goto 10....|
00000020  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  |................|
*
00000400
+ exit 1
```

**Comment by jeromelesaux** [comment]
New issue fixed in 0.29 version

**Comment by jeromelesaux** [comment]
fixed in this version https://github.com/jeromelesaux/dsk/releases/tag/v0.29

**Comment by karme** [comment]
hmm, I still get the mismatch, but maybe my expectation is wrong?

```
$ ./test-bas.sh
+ dsk -dsk test.dsk -format -force
DSK cli version [0.29]
Made by Sid (ImpAct)
Formating number of sectors (9), tracks (39), head number (1)
Dsk file (test.dsk)
+ cat
+ unix2dos test.bas
unix2dos: Datei test.bas wird ins DOS-Format umgewandelt …
+ cat test.bas
10 print "hello"
20 goto 10
+ dsk -dsk test.dsk -list
DSK cli version [0.29]
Made by Sid (ImpAct)
Dsk file (test.dsk)
Dsk 000 Ko used
Dsk 000 Ko used
++ md5sum test.bas
++ cut -f 1 -d ' '
+ X=e8c3630a87ce2ccf5741b13acdf78c38
+ dsk -dsk test.dsk -put test.bas
DSK cli version [0.29]
Made by Sid (ImpAct)
Dsk file (test.dsk)
file (test.bas) read (30 bytes).
No header found for file :test.bas, error :unexpected EOF
File has already header...(test.bas)
DSK path [test.dsk]
ACTION: Action on DSK [put ascii] on amsdos file [test.bas]
INFO:   execute address [#0000], loading address [#0000]

+ rm -v test.bas
'test.bas' wurde entfernt
+ dsk -dsk test.dsk -get test.bas -stdout
DSK cli version [0.29]
Made by Sid (ImpAct)
Dsk file (test.dsk)
++ md5sum test.bas
++ cut -f 1 -d ' '
+ Y=4c8448ae521a46bd0cdd9dff3f2e8790
+ '[' e8c3630a87ce2ccf5741b13acdf78c38 = 4c8448ae521a46bd0cdd9dff3f2e8790 ']'
+ echo MISMATCH
MISMATCH
+ hd test.bas
00000000  31 30 20 70 72 69 6e 74  20 22 68 65 6c 6c 6f 22  |10 print "hello"|
00000010  0d 0a 32 30 20 67 6f 74  6f 20 31 30 0d 0a 1a 00  |..20 goto 10....|
00000020  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  |................|
*
00000400
+ exit 1
```

**Comment by jeromelesaux** [comment]
Yep normal. 
When you store an ascii file on floppy you reserve a block of 512 bytes. 
So when you extract this file from floppy, the size is unknown because it’s stored in the header. By consequence when you extract an ascii file, the size file is a multiple of 512 bytes. In your case the file extract is longer than you original file.
